# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# FIXME - is this just removed, or will that break e.g. the Vivado bitstream flow?
# load("//rules/opentitan:splice.bzl", universal_splice = "bitstream_splice")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "none",
    srcs = ["skip.bit"],
)
