// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module rv_dm_regs_reg_top
  # (
    parameter bit          EnableRacl           = 1'b0,
    parameter bit          RaclErrorRsp         = 1'b1,
    parameter top_racl_pkg::racl_policy_sel_t RaclPolicySelVec[rv_dm_reg_pkg::NumRegsRegs] =
      '{rv_dm_reg_pkg::NumRegsRegs{0}}
  ) (
  input clk_i,
  input rst_ni,
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,
  // To HW
  output rv_dm_reg_pkg::rv_dm_regs_reg2hw_t reg2hw, // Write

  // RACL interface
  input  top_racl_pkg::racl_policy_vec_t racl_policies_i,
  output top_racl_pkg::racl_error_log_t  racl_error_o,

  // Integrity check errors
  output logic intg_err_o
);

  import rv_dm_reg_pkg::* ;

  localparam int AW = 4;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;


  // incoming payload check
  logic intg_err;
  tlul_cmd_intg_chk u_chk (
    .tl_i(tl_i),
    .err_o(intg_err)
  );

  // also check for spurious write enables
  logic reg_we_err;
  logic [2:0] reg_we_check;
  prim_reg_we_check #(
    .OneHotWidth(3)
  ) u_prim_reg_we_check (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oh_i  (reg_we_check),
    .en_i  (reg_we && !addrmiss),
    .err_o (reg_we_err)
  );

  logic err_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      err_q <= '0;
    end else if (intg_err || reg_we_err) begin
      err_q <= 1'b1;
    end
  end

  // integrity error output is permanent and should be used for alert generation
  // register errors are transactional
  assign intg_err_o = err_q | intg_err | reg_we_err;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(1),
    .EnableDataIntgGen(1)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;

  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    // Translate RACL error to TLUL error if enabled
    .error_i (reg_error | (RaclErrorRsp & racl_error_o.valid))
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = addrmiss | wr_err | intg_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic alert_test_we;
  logic alert_test_wd;
  logic late_debug_enable_regwen_we;
  logic late_debug_enable_regwen_qs;
  logic late_debug_enable_regwen_wd;
  logic late_debug_enable_we;
  logic [31:0] late_debug_enable_qs;
  logic [31:0] late_debug_enable_wd;

  // Register instances
  // R[alert_test]: V(True)
  logic alert_test_qe;
  logic [0:0] alert_test_flds_we;
  assign alert_test_qe = &alert_test_flds_we;
  prim_subreg_ext #(
    .DW    (1)
  ) u_alert_test (
    .re     (1'b0),
    .we     (alert_test_we),
    .wd     (alert_test_wd),
    .d      ('0),
    .qre    (),
    .qe     (alert_test_flds_we[0]),
    .q      (reg2hw.alert_test.q),
    .ds     (),
    .qs     ()
  );
  assign reg2hw.alert_test.qe = alert_test_qe;


  // R[late_debug_enable_regwen]: V(False)
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessW0C),
    .RESVAL  (1'h1),
    .Mubi    (1'b0)
  ) u_late_debug_enable_regwen (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (late_debug_enable_regwen_we),
    .wd     (late_debug_enable_regwen_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (),
    .ds     (),

    // to register interface (read)
    .qs     (late_debug_enable_regwen_qs)
  );


  // R[late_debug_enable]: V(False)
  // Create REGWEN-gated WE signal
  logic late_debug_enable_gated_we;
  assign late_debug_enable_gated_we = late_debug_enable_we & late_debug_enable_regwen_qs;
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h69696969),
    .Mubi    (1'b1)
  ) u_late_debug_enable (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (late_debug_enable_gated_we),
    .wd     (late_debug_enable_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.late_debug_enable.q),
    .ds     (),

    // to register interface (read)
    .qs     (late_debug_enable_qs)
  );



  logic [$clog2(NumRegsRegs)-1:0] addr_idx;
  logic addr_valid;
  top_racl_pkg::racl_role_vec_t racl_role_vec;
  top_racl_pkg::racl_role_t racl_role;

  logic [$clog2(NumRegsRegs)-1:0] racl_addr_read_idx;
  logic [$clog2(NumRegsRegs)-1:0] racl_addr_write_idx;
  logic racl_addr_read_valid;
  logic racl_addr_write_valid;

  if (EnableRacl) begin : gen_racl_role_logic
    // Retrieve RACL role from user bits and one-hot encode that for the comparison bitmap
    assign racl_role = top_racl_pkg::tlul_extract_racl_role_bits(tl_i.a_user.rsvd);

    prim_onehot_enc #(
      .OneHotWidth( $bits(top_racl_pkg::racl_role_vec_t) )
    ) u_racl_role_encode (
      .in_i ( racl_role     ),
      .en_i ( 1'b1          ),
      .out_o( racl_role_vec )
    );
  end else begin : gen_no_racl_role_logic
    assign racl_role     = '0;
    assign racl_role_vec = '0;
  end

  always_comb begin
    addr_idx = '0;
    addr_valid = 0;
    racl_addr_read_idx = '0;
    racl_addr_write_idx = '0;
    racl_addr_read_valid = 0;
    racl_addr_write_valid = 0;
    unique case (reg_addr)
      // TODO: use the register index enum entries instead?
      RV_DM_ALERT_TEST_OFFSET: begin addr_valid = 1; addr_idx = 0; end
      RV_DM_LATE_DEBUG_ENABLE_REGWEN_OFFSET: begin addr_valid = 1; addr_idx = 1; end
      RV_DM_LATE_DEBUG_ENABLE_OFFSET: begin addr_valid = 1; addr_idx = 2; end
      default: begin addr_valid = 0; addr_idx = '0; end
    endcase

    if (EnableRacl) begin : gen_racl_hit
      if (|(racl_policies_i[RaclPolicySelVec[addr_idx]].read_perm & racl_role_vec)) begin
        racl_addr_read_idx = addr_idx;
        racl_addr_read_valid = addr_valid;
      end
      if (|(racl_policies_i[RaclPolicySelVec[addr_idx]].write_perm & racl_role_vec)) begin
        racl_addr_write_idx = addr_idx;
        racl_addr_write_valid = addr_valid;
      end
    end else begin : gen_no_racl
      racl_addr_read_idx = addr_idx;
      racl_addr_write_idx = addr_idx;
      racl_addr_read_valid = addr_valid;
      racl_addr_write_valid = addr_valid;
    end
  end

  assign addrmiss = (reg_re || reg_we) ? ~addr_valid : 1'b0 ;
  // A valid address hit, access, but failed the RACL check
  assign racl_error_o.valid = addr_valid & ((reg_re & ~racl_addr_read_valid) |
                                            (reg_we & ~racl_addr_write_valid));
  assign racl_error_o.request_address = top_pkg::TL_AW'(reg_addr);
  assign racl_error_o.racl_role       = racl_role;
  assign racl_error_o.overflow        = 1'b0;

  if (EnableRacl) begin : gen_racl_log
    assign racl_error_o.ctn_uid     = top_racl_pkg::tlul_extract_ctn_uid_bits(tl_i.a_user.rsvd);
    assign racl_error_o.read_access = tl_i.a_opcode == tlul_pkg::Get;
  end else begin : gen_no_racl_log
    assign racl_error_o.ctn_uid     = '0;
    assign racl_error_o.read_access = 1'b0;
  end

  // Check sub-word write is permitted
  always_comb begin
    wr_err = 0;

    if (reg_we && racl_addr_write_valid) begin
      case (racl_addr_write_idx)
        // TODO: use the register index enum entries instead?
        0: wr_err = |(RV_DM_REGS_PERMIT[0] & ~reg_be);
        1: wr_err = |(RV_DM_REGS_PERMIT[1] & ~reg_be);
        2: wr_err = |(RV_DM_REGS_PERMIT[2] & ~reg_be);
      endcase
    end
  end

  // Generate write-enables
  assign alert_test_we = racl_addr_write_valid & (racl_addr_write_idx == 0) & reg_we & !reg_error;

  assign alert_test_wd = reg_wdata[0];

  assign late_debug_enable_regwen_we = racl_addr_write_valid & (racl_addr_write_idx == 1) & reg_we & !reg_error;

  assign late_debug_enable_regwen_wd = reg_wdata[0];

  assign late_debug_enable_we = racl_addr_write_valid & (racl_addr_write_idx == 2) & reg_we & !reg_error;

  assign late_debug_enable_wd = reg_wdata[31:0];


  // Assign write-enables to checker logic vector.
  always_comb begin
    reg_we_check[0] = alert_test_we;
    reg_we_check[1] = late_debug_enable_regwen_we;
    reg_we_check[2] = late_debug_enable_gated_we;
  end

  // Read data return
  always_comb begin
    if (!racl_addr_read_valid) begin
      reg_rdata_next = '1;
    end else begin
      reg_rdata_next = '0;
      unique case (racl_addr_read_idx)
        // TODO: use the register index enum entries instead?
        0: begin
          reg_rdata_next[0] = '0;
        end

        1: begin
          reg_rdata_next[0] = late_debug_enable_regwen_qs;
        end

        2: begin
          reg_rdata_next[31:0] = late_debug_enable_qs;
        end

      default: begin
        reg_rdata_next = '1;
      end
      endcase
    end
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;
  logic unused_policy_sel;
  assign unused_policy_sel = ^racl_policies_i;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> addr_valid, clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)

endmodule
