# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Azure Release Pipeline configuration
# Documentation at https://aka.ms/yaml

schedules:
# Run this pipeline every Sunday at 07:21 UTC.
# Use an arbitrary minute value to avoid congestion on the hour.
- cron: "0 21 7 * * SUN"
  displayName: "OpenTitan Weekly Tests"
  branches:
    include:
    - "master"
  always: True

trigger: none
pr: none

variables:
  # If updating VERILATOR_VERSION, TOOLCHAIN_VERSION, update
  # the definitions in util/container/Dockerfile as well.
  VERILATOR_VERSION: 4.210
  TOOLCHAIN_PATH: /opt/buildcache/riscv
  VERIBLE_VERSION: v0.0-3622-g07b310a3
    # Release tag from https://github.com/lowRISC/lowrisc-toolchains/releases
  TOOLCHAIN_VERSION: 20220210-1
    # This controls where builds happen, and gets picked up by build_consts.sh.
  BUILD_ROOT: $(Build.ArtifactStagingDirectory)
  VIVADO_VERSION: "2021.1"

jobs:
- job: checkout
  displayName: "Checkout repository"
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    # Set fetchDepth to 0 to pull the entire git tree for the bitstream cache to work
    # https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout#shallow-fetch
    fetchDepth: 0
    path: opentitan-repo
  - bash: |
      tar -C $(Pipeline.Workspace)/opentitan-repo -czf $(Pipeline.Workspace)/opentitan-repo.tar.gz .
    displayName: "Pack up repository"
  - publish: $(Pipeline.Workspace)/opentitan-repo.tar.gz
    artifact: opentitan-repo
    displayName: "Upload repository"

- job: verilator_tests
  displayName: "Verilator Tests"
  timeoutInMinutes: 0
  dependsOn: checkout
  pool: ci-public
  steps:
  - template: ../ci/checkout-template.yml
  - template: ../ci/install-package-dependencies.yml
  - bash: |
      set -x
      ci/bazelisk.sh test \
        --build_tests_only \
        --test_output=errors \
        --local_test_jobs=8 \
        --local_cpu_resources=8 \
        --test_timeout=2400,2400,3600,-1 \
        --test_tag_filters=verilator,-broken \
        --//hw:verilator_options=--threads,1 \
        --//hw:make_options=-j,8 \
        $(bash ./bazelisk.sh query 'tests(//...) except attr("tags", "nightly", tests(//sw/otbn/crypto/...))')
    displayName: "Run all Verilator Tests"
  - template: ../ci/publish-bazel-test-results.yml
